name: riverpodding
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter_hooks: ^0.18.6
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.10.0
  hooks_riverpod: ^2.3.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.0
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.0
  custom_lint: ^0.2.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  functional_widget: ^0.10.1
  json_serializable: ^6.6.1
  riverpod_generator: ^2.0.0
  riverpod_lint: ^1.1.2

flutter:
  uses-material-design: true
